"""
Trip model — an AI-suggested (or user-confirmed) trip.

Each trip belongs to a user and maps to a travel window from the Calendar Engine.

Fields:
  - destination_id  : links to the Destination table
  - start_date      : trip start
  - end_date        : trip end
  - duration_days   : convenience field (end - start + 1)
  - estimated_budget: total estimated cost in INR
  - itinerary_json  : the day-by-day plan (generated by AI), stored as JSON
  - status          : "suggested" → "confirmed" → "completed"
  - match_score     : how well this trip matches the user's preferences (0-100%)
"""

import uuid
from datetime import date, datetime

from sqlalchemy import Date, DateTime, Float, ForeignKey, Integer, SmallInteger, String, Text, func
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base


class Trip(Base):
    __tablename__ = "trips"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE")
    )
    destination_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("destinations.id", ondelete="SET NULL")
    )

    title: Mapped[str] = mapped_column(String(200), nullable=False)       # e.g., "Holi Weekend in Goa"
    start_date: Mapped[date] = mapped_column(Date, nullable=False)
    end_date: Mapped[date] = mapped_column(Date, nullable=False)
    duration_days: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    estimated_budget: Mapped[int | None] = mapped_column(Integer)         # INR
    itinerary: Mapped[dict | None] = mapped_column(JSONB)                 # day-by-day plan
    status: Mapped[str] = mapped_column(String(20), default="suggested")  # suggested/confirmed/completed
    match_score: Mapped[float | None] = mapped_column(Float)              # 0.0 - 1.0
    notes: Mapped[str | None] = mapped_column(Text)                       # user notes

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

    # Relationships
    user = relationship("User", back_populates="trips")
    destination = relationship("Destination", back_populates="trips")
